name: Build JavaFX App

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build JAR
        run: mvn clean package

      # macOS installer
      - name: Create DMG installer
        if: runner.os == 'macOS'
        run: |
          jpackage \
            --name MyApp \
            --input target/ \
            --main-jar MakanFinder-1.0-SNAPSHOT.jar \
            --type dmg \
           --icon installer/icon.icns

      # Windows installer
      - name: Create EXE installer
        if: runner.os == 'Windows'
        run: |
          jpackage `
            --name MyApp `
            --input target\ `
            --main-jar MakanFinder-1.0-SNAPSHOT.jar `
            --type exe `
            --icon installer\icon.ico
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyJavaFXApp
          path: |
            *.dmg
            *.exe